### ISSUE TITLE
Monitor Mode not working

### ISSUE THREAD

**Issue by tgupta3** [pvaret/rtl8192cu-fixes#10]
Hello,

Thanks for the driver. While using it, iwconfig doesn't show tx power of the adaptor. Also when i try to put the adaptor in monitor mode, no interface gets assigned .

Thanks

**Comment by pvaret** [comment]
As a late update: the rtl8xxxu driver from the mainline kernel works pretty fine these days. That's what I'm using now myself. You may still have to troubleshoot NetworkManager, though: in particular, consider [disabling power management](https://askubuntu.com/questions/695867/disable-wifi-power-management/961460#961460). Disabling it made the rtlxxxu driver work well for me.
