### ISSUE TITLE
ASUSTek N10 Nano

### ISSUE THREAD

**Issue by Lazzu** [pvaret/rtl8192cu-fixes#100]
The connection dropped constantly on my Ubuntu 16.4 desktop with the N10 Nano, so I installed this driver instead. Now I haven't experienced a single connection drop after that. But my speed still isn't the same and the ping is going everywhere. I'm not sure if it's because my AP is also my Nexus 6 Android phone, but I haven't experienced anything like this on my lenovo laptop using wireless. Also when I plug my phone to my desktop with USB and share the internet that way, I get the full 100mbps connection I should be getting from the phone. With wifi my download speed is only about 40mbps when testing with speedtest.

But hey, at least it hasn't disconnected yet! That was the most irritating issue and now I'm happy using the wlan dongle again. The other issues I am mentioning might as well be caused because I am using the phone as my AP. Also the mobile network I am using is known for not always giving 100% of the highest of speeds for the users, so it might be that too.

lsusb:
`ID 0b05:17ba ASUSTek Computer, Inc. N10 Nano 802.11n Network Adapter [Realtek RTL8192CU]`

My ping when browsing the web normally:

```
64 bytes from lasse.pw (144.76.81.227): icmp_seq=1729 ttl=55 time=54.6 ms
64 bytes from lasse.pw (144.76.81.227): icmp_seq=1730 ttl=55 time=102 ms
64 bytes from lasse.pw (144.76.81.227): icmp_seq=1731 ttl=55 time=195 ms
64 bytes from lasse.pw (144.76.81.227): icmp_seq=1732 ttl=55 time=218 ms
64 bytes from lasse.pw (144.76.81.227): icmp_seq=1733 ttl=55 time=1489 ms
64 bytes from lasse.pw (144.76.81.227): icmp_seq=1734 ttl=55 time=653 ms
64 bytes from lasse.pw (144.76.81.227): icmp_seq=1735 ttl=55 time=46.1 ms
64 bytes from lasse.pw (144.76.81.227): icmp_seq=1736 ttl=55 time=166 ms
64 bytes from lasse.pw (144.76.81.227): icmp_seq=1737 ttl=55 time=49.3 ms
64 bytes from lasse.pw (144.76.81.227): icmp_seq=1738 ttl=55 time=114 ms
64 bytes from lasse.pw (144.76.81.227): icmp_seq=1739 ttl=55 time=49.6 ms
64 bytes from lasse.pw (144.76.81.227): icmp_seq=1740 ttl=55 time=45.1 ms
64 bytes from lasse.pw (144.76.81.227): icmp_seq=1741 ttl=55 time=121 ms
64 bytes from lasse.pw (144.76.81.227): icmp_seq=1742 ttl=55 time=158 ms
64 bytes from lasse.pw (144.76.81.227): icmp_seq=1743 ttl=55 time=116 ms
64 bytes from lasse.pw (144.76.81.227): icmp_seq=1744 ttl=55 time=150 ms
64 bytes from lasse.pw (144.76.81.227): icmp_seq=1745 ttl=55 time=114 ms
64 bytes from lasse.pw (144.76.81.227): icmp_seq=1746 ttl=55 time=232 ms
64 bytes from lasse.pw (144.76.81.227): icmp_seq=1747 ttl=55 time=111 ms
64 bytes from lasse.pw (144.76.81.227): icmp_seq=1748 ttl=55 time=44.6 ms
64 bytes from lasse.pw (144.76.81.227): icmp_seq=1749 ttl=55 time=48.3 ms
```

The ping goes to 400ms - 500ms when downloading a large file.

**Comment by pvaret** [comment]
As a late update: I found that instability was often caused by power management issues. That being said, now, the rtl8xxxu driver from the mainline kernel works pretty fine these days. That's what I'm using now myself. You may still have to troubleshoot NetworkManager, though: in particular, consider [disabling power management](https://askubuntu.com/questions/695867/disable-wifi-power-management/961460#961460). Disabling it made the rtlxxxu driver work well for me.
