### ISSUE TITLE
ubuntu 16.04 ASUSTek Nano 802.11n wireless adapter

### ISSUE THREAD

**Issue by redheli** [pvaret/rtl8192cu-fixes#104]
Hi,

  recently I install dual system ubuntu 16.04 and 14.04 . the driver works perfect on ubuntu 14.04 with asus nano wifi adapter.

  but no luck on 16.04.
  I followed install steps, no error popup.

I tried [ASUSTek N10 Nano #100](https://github.com/pvaret/rtl8192cu-fixes/issues/100), but still not work.

please help!!!

  here is my system info:
uname -a

> Linux max-Alienware-15 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

 lsusb

> Bus 002 Device 002: ID 8087:8000 Intel Corp. 
> Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
> Bus 001 Device 002: ID 8087:8008 Intel Corp. 
> Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
> Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
> Bus 003 Device 007: ID 0cf3:3004 Atheros Communications, Inc. AR3012 Bluetooth 4.0
> Bus 003 Device 009: ID 0b05:17ba ASUSTek Computer, Inc. N10 Nano 802.11n Network Adapter [Realtek RTL8192CU]
> Bus 003 Device 003: ID 187c:0528 Alienware Corporation 
> Bus 003 Device 006: ID 046d:c07d Logitech, Inc. 
> Bus 003 Device 005: ID 1bcf:28b6 Sunplus Innovation Technology Inc. 
> Bus 003 Device 004: ID 04f3:2061 Elan Microelectronics Corp. 
> Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
> 

sudo lshw -C network
  

> *-network               
>        description: Ethernet interface
>        product: Killer E220x Gigabit Ethernet Controller
>        vendor: Qualcomm Atheros
>        physical id: 0
>        bus info: pci@0000:02:00.0
>        logical name: enp2s0
>        version: 10
>        serial: 34:e6:d7:3c:39:90
>        size: 1Gbit/s
>        capacity: 1Gbit/s
>        width: 64 bits
>        clock: 33MHz
>        capabilities: pm pciexpress msi msix bus_master cap_list ethernet physical tp 10bt 10bt-fd 100bt 100bt-fd 1000bt-fd autonegotiation
>        configuration: autonegotiation=on broadcast=yes driver=alx duplex=full ip=192.168.1.2 latency=0 link=yes multicast=yes port=twisted pair speed=1Gbit/s
>        resources: irq:42 memory:f7400000-f743ffff ioport:d000(size=128)
>   *-network DISABLED
>        description: Wireless interface
>        product: QCA6174 802.11ac Wireless Network Adapter
>        vendor: Qualcomm Atheros
>        physical id: 0
>        bus info: pci@0000:03:00.0
>        logical name: wlp3s0
>        version: 20
>        serial: ac:d1:b8:73:fc:47
>        width: 64 bits
>        clock: 33MHz
>        capabilities: pm msi pciexpress bus_master cap_list ethernet physical wireless
>        configuration: broadcast=yes driver=ath10k_pci driverversion=4.4.0-45-generic firmware=SW_RM.1.1.1-00157-QCARMSWPZ-1 latency=0 link=no multicast=yes wireless=IEEE 802.11abgn
>        resources: irq:34 memory:f6800000-f69fffff
>   *-network DISABLED
>        description: Wireless interface
>        physical id: 2
>        bus info: usb@3:5
>        logical name: wlx1c872cc63ee0
>        serial: 1c:87:2c:c6:3e:e0
>        capabilities: ethernet physical wireless
>        configuration: broadcast=yes driver=rtl8192cu multicast=yes wireless=unassociated

lsmod

> Module                  Size  Used by
> 8192cu                532480  0
> bnep                   20480  2
> bbswitch               16384  0
> appletalk              36864  0
> ipx                    28672  0
> p8023                  16384  1 ipx
> p8022                  16384  1 ipx
> psnap                  16384  2 ipx,appletalk
> llc                    16384  2 p8022,psnap
> nls_iso8859_1          16384  1
> arc4                   16384  2
> ath3k                  20480  0
> btusb                  45056  0
> btrtl                  16384  1 btusb
> btbcm                  16384  1 btusb
> btintel                16384  1 btusb
> bluetooth             520192  10 bnep,ath3k,btbcm,btrtl,btusb,btintel
> dell_wmi               16384  0
> sparse_keymap          16384  1 dell_wmi
> mxm_wmi                16384  0
> intel_rapl             20480  0
> x86_pkg_temp_thermal    16384  0
> intel_powerclamp       16384  0
> coretemp               16384  0
> kvm_intel             172032  0
> kvm                   540672  1 kvm_intel
> uvcvideo               90112  0
> ath10k_pci             45056  0
> ath10k_core           311296  1 ath10k_pci
> nvidia_uvm            745472  0
> irqbypass              16384  1 kvm
> ath                    32768  1 ath10k_core
> videobuf2_vmalloc      16384  1 uvcvideo
> mac80211              737280  1 ath10k_core
> videobuf2_memops       16384  1 videobuf2_vmalloc
> videobuf2_v4l2         28672  1 uvcvideo
> videobuf2_core         36864  2 uvcvideo,videobuf2_v4l2
> v4l2_common            16384  1 videobuf2_v4l2
> snd_hda_codec_hdmi     53248  1
> videodev              176128  4 uvcvideo,v4l2_common,videobuf2_core,videobuf2_v4l2
> hid_multitouch         20480  0
> media                  24576  2 uvcvideo,videodev
> input_leds             16384  0
> snd_hda_codec_ca0132    57344  1
> joydev                 20480  0
> cfg80211              565248  3 ath,mac80211,ath10k_core
> serio_raw              16384  0
> snd_soc_rt5640        114688  0
> snd_hda_intel          40960  5
> snd_soc_rl6231         16384  1 snd_soc_rt5640
> rtsx_pci_ms            20480  0
> snd_soc_ssm4567        16384  0
> snd_hda_codec         135168  3 snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec_ca0132
> memstick               20480  1 rtsx_pci_ms
> snd_hda_core           73728  4 snd_hda_codec_hdmi,snd_hda_codec,snd_hda_intel,snd_hda_codec_ca0132
> snd_soc_core          212992  2 snd_soc_rt5640,snd_soc_ssm4567
> snd_hwdep              16384  1 snd_hda_codec
> ie31200_edac           16384  0
> mei_me                 36864  0
> edac_core              53248  1 ie31200_edac
> mei                    98304  1 mei_me
> snd_compress           20480  1 snd_soc_core
> ac97_bus               16384  1 snd_soc_core
> lpc_ich                24576  0
> snd_pcm_dmaengine      16384  1 snd_soc_core
> snd_pcm               106496  7 snd_soc_rt5640,snd_soc_core,snd_hda_codec_hdmi,snd_hda_codec,snd_hda_intel,snd_pcm_dmaengine,snd_hda_core
> shpchp                 36864  0
> snd_seq_midi           16384  0
> snd_seq_midi_event     16384  1 snd_seq_midi
> snd_rawmidi            32768  1 snd_seq_midi
> snd_seq                69632  2 snd_seq_midi_event,snd_seq_midi
> snd_seq_device         16384  3 snd_seq,snd_rawmidi,snd_seq_midi
> int3403_thermal        16384  0
> snd_timer              32768  2 snd_pcm,snd_seq
> snd                    81920  22 snd_soc_core,snd_hwdep,snd_timer,snd_hda_codec_hdmi,snd_pcm,snd_seq,snd_rawmidi,snd_hda_codec,snd_hda_intel,snd_seq_device,snd_compress,snd_hda_codec_ca0132
> wmi                    20480  2 dell_wmi,mxm_wmi
> elan_i2c               36864  0
> soundcore              16384  1 snd
> snd_soc_sst_acpi       16384  0
> 8250_dw                16384  0
> int3402_thermal        16384  0
> dw_dmac                16384  0
> int340x_thermal_zone    16384  2 int3402_thermal,int3403_thermal
> dw_dmac_core           24576  1 dw_dmac
> i2c_designware_platform    16384  0
> int3400_thermal        16384  0
> i2c_designware_core    20480  1 i2c_designware_platform
> dell_rbtn              16384  0
> acpi_thermal_rel       16384  1 int3400_thermal
> spi_pxa2xx_platform    24576  0
> acpi_als               16384  0
> mac_hid                16384  0
> acpi_pad               20480  0
> kfifo_buf              16384  1 acpi_als
> industrialio           57344  2 acpi_als,kfifo_buf
> sunrpc                335872  1
> parport_pc             32768  0
> ppdev                  20480  0
> lp                     20480  0
> parport                49152  3 lp,ppdev,parport_pc
> autofs4                40960  2
> drbg                   32768  1
> ansi_cprng             16384  0
> algif_skcipher         20480  0
> af_alg                 16384  1 algif_skcipher
> dm_crypt               28672  1
> hid_generic            16384  0
> usbhid                 49152  0
> psmouse               126976  0
> rtsx_pci_sdmmc         24576  0
> i915                 1208320  3
> crct10dif_pclmul       16384  0
> crc32_pclmul           16384  0
> nvidia_drm             53248  1
> nvidia_modeset        778240  4 nvidia_drm
> aesni_intel           167936  2
> i2c_algo_bit           16384  1 i915
> aes_x86_64             20480  1 aesni_intel
> drm_kms_helper        155648  2 i915,nvidia_drm
> lrw                    16384  1 aesni_intel
> gf128mul               16384  1 lrw
> syscopyarea            16384  1 drm_kms_helper
> glue_helper            16384  1 aesni_intel
> sysfillrect            16384  1 drm_kms_helper
> ablk_helper            16384  1 aesni_intel
> sysimgblt              16384  1 drm_kms_helper
> ahci                   36864  3
> cryptd                 20480  3 aesni_intel,ablk_helper
> fb_sys_fops            16384  1 drm_kms_helper
> alx                    36864  0
> nvidia              11931648  71 nvidia_modeset,nvidia_uvm
> libahci                32768  1 ahci
> rtsx_pci               53248  2 rtsx_pci_ms,rtsx_pci_sdmmc
> drm                   364544  9 i915,drm_kms_helper,nvidia_drm
> mdio                   16384  1 alx
> sdhci_acpi             16384  0
> sdhci                  45056  1 sdhci_acpi
> video                  40960  2 i915,dell_wmi
> i2c_hid                20480  0
> hid                   118784  4 i2c_hid,hid_multitouch,hid_generic,usbhid
> fjes                   28672  0
>

**Comment by pvaret** [comment]
I'm not sure why your device is shown as disabled. Are "Enable Networking" and "Enable WiFi" both checked in Network Manager?

Note that your other WiFi device (Qualcomm Atheros) is also disabled, so this doesn't look like an issue with this driver.

**Comment by redheli** [comment]
@pvaret yes, I think it is not driver problem. maybe it is ubuntu network manager problem, I installed wicd and it can connect to wifi with no problem. 
thanks a lot. your work is awesome.

**Comment by pvaret** [comment]
Hey @redheli, glad your problem is solved! And thank you for your kind words, although as I've said elsewhere, the work isn't really ours; this repo is only a repackaging of the official Realtek driver to make it work on more recent Linux versions, that's all. :)
