### ISSUE TITLE
Working: Kootek RTL8188CUS-based USB adapter

### ISSUE THREAD

**Issue by davidmreed** [pvaret/rtl8192cu-fixes#105]
lsusb:

`Bus 002 Device 003: ID 0bda:8176 Realtek Semiconductor Corp. RTL8188CUS 802.11n WLAN Adapter
`

[This](https://www.amazon.com/gp/product/B00FWMEFES/ref=oh_aui_search_detailpage?ie=UTF8&psc=1) is the product on Amazon.

**Comment by dlech** [comment]
I've added to the README. Thanks for sharing.
