### ISSUE TITLE
Wifi not showing up, 16.04 [TP-Link TL-WN823N]

### ISSUE THREAD

**Issue by D4RKONION** [pvaret/rtl8192cu-fixes#107]
Hi there.

I followed the instructions in the readme and everything seemed to install without a hitch. However, there is still no wifi options coming up. Please advise

Thanks for all the work you've done on this project!

**Comment by dlech** [comment]
There may be some helpful information in these [existing issues about 16.04](https://github.com/pvaret/rtl8192cu-fixes/search?q=16.04&type=Issues&utf8=%E2%9C%93)

**Comment by D4RKONION** [comment]
I had read those alright, didn't see anything matching my own issues. One person mentions enabling wifi in the network manager, but I'm seeing no option like that.

**Comment by samohovets** [comment]
Same problem

**Comment by jeremyb31** [comment]
Some of the TL-WN823N's do not use the rtl8192cu chipset.  If lsusb results show ID 2357:0107, 2357:0108, or 2357:0109 you should use https://github.com/Mange/rtl8192eu-linux-driver as these are rtl8192eu chipsets

**Comment by robertholding** [comment]
@jeremyb31 ，this is a right way to install the driver, thank you,

**Comment by shashishailaj** [comment]
@robertholding  , It  (https://github.com/Mange/rtl8192eu-linux-driver ) worked for me without a problem with TP-LINK TL-WN823N V2 WiFi adapter running on KDE neon 4.9.2 (based on Ubuntu 16.04 LTS) Kernel 4.8. 

Try to use the instructions on the github page https://github.com/Mange/rtl8192eu-linux-driver . It must work.

**Comment by robertholding** [comment]
@shashishailaj thanks for your help. it works!
