### ISSUE TITLE
Problems Fixed on Fedora: 26_Alpha, with Kernel: 4.11.0-1.fc26.x86_64

### ISSUE THREAD

**Issue by Pant** [pvaret/rtl8192cu-fixes#117]
I just wanted to mention that everything works on Fedora 26_Alpha and kernel: 4.11.0-1.fc26.x86_64 .
Note that i had to manually copy the "blacklist-native-rtl8192.conf" to "/etc/modprobe.d/" directory.
Device: Edimax EW-7811Un.

**Comment by pvaret** [comment]
Thanks for the info!
