### ISSUE TITLE
Multi SSID AP +AP mode

### ISSUE THREAD

**Issue by hardd2007** [pvaret/rtl8192cu-fixes#118]
Good day. I compile driver with concurrent=1.
Then I compile hostapd for rtl driver. But I can not create tow APs with multi SSIDs.
Have any idea about it?

**Comment by pvaret** [comment]
'Fraid not. But for problems relating to how the driver behaves, you should really contact the upstream maintainers, Realtek themselves. This repo is only a repackaging of their driver to make it work on recent kernels.
