### ISSUE TITLE
Does not work with Anewkodi USB unit on Zorin

### ISSUE THREAD

**Issue by sawmilldon** [pvaret/rtl8192cu-fixes#119]
I ran through all these commands and there is no change in function on my new build.

**Comment by pvaret** [comment]
I dug in a little and it doesn't look like your device uses the rtl8192cu chipset. So this driver is definitely not what you need. Consider using the rtl8xxxu driver from the mainline kernel and troubleshooting NetworkManager itself, which has been a common source of problems for people. In particular look into [disabling power management](https://askubuntu.com/questions/695867/disable-wifi-power-management/961460#961460); it made the rtlxxxu driver work for me.
