### ISSUE TITLE
Stability issues

### ISSUE THREAD

**Issue by cfusting** [pvaret/rtl8192cu-fixes#12]
This driver worked very well initially, but something seems to be very wrong?  My speeds went from ~40 mbs to 2.  Same thing happened recently on Arch Linux when I updated the system.  I suspect newer kernels do not play nice.

**Comment by pvaret** [comment]
No news about this, so closing for now.

**Comment by FVerbum** [comment]
Hello.
I use this driver for USB dongle EDUP EP-MS1537 (8192CU) on Ubuntu 14.04 (3.13.0-45-generic).
Unfortunately I can't setup Ad-Hoc mode (static ip without wpa) - network manager say that all ok - connect on,
but I can't ping any comp in net.
I tried without network manager (unmanaged-devices and settings in .../interfaces) same result.
In same time internal wifi adapter Intel 2200 works without problem.
And this dongle on RaspberryPi (Raspbian 3.12.35+) in Ad-Hoc mode works without problem.
Can you help me?

**Comment by pvaret** [comment]
Answered in #32.
