### ISSUE TITLE
confirmed working with OurLink USB adapter

### ISSUE THREAD

**Issue by bobsol** [pvaret/rtl8192cu-fixes#122]
This fix is confirmed working well with an OurLink USB device, adafruit pn 1012, lsusb reports:ID 0bda:8176 Realtek Semiconductor Corp. RTL8188CUS 802.11n WLAN Adapter

I am sure it's lame to report this as an issue, but cant figure out how else to do it...

Thank you.

**Comment by pvaret** [comment]
You did exactly the right thing in the right way with the right information. Thank you for the report. :)

**Comment by bobsol** [comment]
Ty.
