### ISSUE TITLE
moniter mode kali linux

### ISSUE THREAD

**Issue by mohammedhassannai** [pvaret/rtl8192cu-fixes#129]
am running kali with kernel SMP Debian 4.14.2-1kali1 which rtl81xxxu driver wont run on it as it run on 4.4 and newer and i use the blacklist conf in your fix and still the phy is null plz help me i can not start moniter mode on my device and i have much work to do

**Comment by mohammedhassannai** [comment]
your fix working perfect and i am able to connect to any network but the only issue is that moniter mode

**Comment by pvaret** [comment]
Monitor mode doesn't work in Realtek's driver. Use rtl8xxxu as advised in the other thread.
