### ISSUE TITLE
No PKGBUILD for manjaro and arch

### ISSUE THREAD

**Issue by Austcool-Walker** [pvaret/rtl8192cu-fixes#141]
I can’t build a arch package for manjaro for installing and backing up the pkg.tar.xz

**Comment by pvaret** [comment]
This repo is for Ubuntu. I understand that some people from Arch use it in one of their packages, but I don't know anything about that. Please bring issues with the Arch package to the people that make the Arch package, as I'm not going to be able to help.

Also please consider switching to the in-kernel driver instead (rtl8xxxu) and report issues with it, if any, to the kernel maintainers. This repo here is a horrible pile of kludges to make an old vendor driver compile on recent kernels, and the very fact people still need it makes me sad. :)
