### ISSUE TITLE
Will it work on kernel versions over 4.15?

### ISSUE THREAD

**Issue by GilbertTheBartender** [pvaret/rtl8192cu-fixes#146]
i do know that the driver is deprecated, but i'm running debian unstable, the rtl8192cu driver doesn't connect, and rtl8xxxu doesn't even recognize the external usb. do i have to downgrade the kernel to 4.15 or will it work on kernel 4.17? (Current version on debian unstable)

**Comment by dlech** [comment]
Why don't you just try it on 4.17 and find out?

**Comment by GilbertTheBartender** [comment]
Just did. no issues on Kernel Versions 4.17 and 4.18 that i can note of.
