### ISSUE TITLE
'rtw_ips_pwr_down' after 'ip link set up' on device

### ISSUE THREAD

**Issue by awrush** [pvaret/rtl8192cu-fixes#15]
Hi,

can't seem to use this with an EDIMAX EW-7811UN USB dongle on Linux 3.15.5 (3.15.5-2-ARCH, Arch Linux 64 Bit).

Compiling the current master (commit f0dfbb46a891820b27942ba3e213af83f2452957) works fine. But every time i try to activate the device via 'ip link set up dev wlan1' it immediately seems to lose power and the driver deinitializes.

[Kernel log gist](https://gist.github.com/awerush/26ed5787f022abf8816e)

How can I help to solve this?

**Comment by pvaret** [comment]
As a late update: the rtl8xxxu driver from the mainline kernel works pretty fine these days. That's what I'm using now myself. You may still have to troubleshoot NetworkManager, though: in particular, consider [disabling power management](https://askubuntu.com/questions/695867/disable-wifi-power-management/961460#961460). Disabling it made the rtlxxxu driver work well for me.
