### ISSUE TITLE
'linux-headers-generic' has no installation candidate in Debain 10 eg Buster

### ISSUE THREAD

**Issue by blub4747** [pvaret/rtl8192cu-fixes#151]
Hi guys,
I am trying to build the driver for my generic USB Wifi module.
eg this guy
https://www.ebay.de/itm/Mini-Wireless-USB-Adapter-LAN-Wifi-Dongle-f-Raspberry-Pi-802-11b-g-n-150Mbps-NE/173169451507?hash=item2851b421f3:m:mVST_TyKCVL55ZXLbs-bajg:rk:1:pf:0
While trying to built it.
I encoutered the following error msg.

> 'linux-headers-generic' has no installation candidate

However please do note that I am using a Debian testing

>  lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux buster/sid
Release:        testing
Codename:       buster

Any advice ?
Thx, blub4747

**Comment by pvaret** [comment]
I took a look. It looks like in Debian you will need to install the specific package for your arch, so probably linux-headers-amd64.
