### ISSUE TITLE
driver not working for raspbian kernel 5.4.51

### ISSUE THREAD

**Issue by MrStashley** [pvaret/rtl8192cu-fixes#165]
I am trying to use this driver to make use of private ioctls for wifi p2p with a raspberry pi and an edimax ew7811un.

When following the install instructions, all of the commands run as if they are working correctly, but once I copy the blacklist-native-drivers.conf and reboot, the driver stops working completely; it isn't showing up in lsmod and the internet isn't working. 

Can anyone help me with this, or is my platform not supported? I really hope I can get this to work because it seems like this driver is the only one that might work on my raspberry pi.

**Comment by gps05** [comment]
You could try deleting all lines in the blacklist-native-drivers.conf file and adding `blacklist rtl8192cu`
Or maybe `install rtl8192cu /bin/false`

**Comment by MrStashley** [comment]
okay thanks! I'll try it. 
Would install rtl8192cu /bin/false also go inside blacklist-native-drivers.conf?

**Comment by MrStashley** [comment]
IT WORKS!!!!!!!
Thank you so much, I think adding 8192cu to /etc/modules made it run. Also there was a blacklist-8192cu.conf in /etc/modprobe.d for some reason that said `blacklist 8192cu`. I think it was accidentally blacklisting the good drivers, I commented it out with # and rebooted and it worked. I now can use wifi P2P and continue working on my project thanks!

**Comment by MrStashley** [comment]
if I close the issue does that mean no one else can comment? What if someone has a similar issue and wants my guidance on what I did to fix mine?

**Comment by dlech** [comment]
anyone can still comment on a closed issue

**Comment by MrStashley** [comment]
Awesome, thanks!
