### ISSUE TITLE
Belkin N300 in Ad Hoc mode

### ISSUE THREAD

**Issue by RedLionNJ** [pvaret/rtl8192cu-fixes#186]
Does anybody know for a fact this driver should work in Ad Hoc mode with the Belkin N300 USB wifi adapter?
I tried the driver with Mint 21 (because the native driver wouldn't connect in Ad Hoc mode) and it appears to have the same issue (won't establish the connection to an Ad Hoc peer).
It looks like perhaps in some of the modules there are comments indicating Ad Hoc specific functionality is still 'to do'?

**Comment by pvaret** [comment]
> Does anybody know for a fact this driver should work in Ad Hoc mode with the Belkin N300 USB wifi adapter?

Nope. Besides, this driver is deprecated and unsupported. If the native driver does not work as expected, the proper escalation path is the kernel maintainers for that driver.
