### ISSUE TITLE
Access point mode

### ISSUE THREAD

**Issue by nikedlab** [pvaret/rtl8192cu-fixes#27]
Hi
I have USB wifi dongle ZyXEL Communications Corp. NWD2205 802.11n Wireless N Adapter [Realtek RTL8192CU]
I bought this dongle for using as access point. Previously I has problems with stable connection on rtl8192cu driver but it worked well as AP.
I install your driver, dongle worked perfectly in infrastructure mode, but I can't setup AP.. Probably your driver not supported AP?

**Comment by pvaret** [comment]
No news about this, so closing for now.
