### ISSUE TITLE
related .deb?

### ISSUE THREAD

**Issue by avimar** [pvaret/rtl8192cu-fixes#30]
I came across this link to a deb and black list instructions:

https://code.google.com/p/realtek-8188cus-wireless-drivers-3444749-ubuntu-1304/

and it seems similar/the same as here (just a package vs compiling), but I don't see that either link to the other.

Should these two be merged or cross-linked?

**Comment by pvaret** [comment]
Oh crap, forgot to respond to this -- sorry!

I do in fact link to Tim's code in the README. Initially, this repo was based on Tim's work, but Realtek since released a more recent version of their driver, and this repo is now based on that version instead of Tim's.
