### ISSUE TITLE
no 5ghz

### ISSUE THREAD

**Issue by leifj** [pvaret/rtl8192cu-fixes#48]
I'm using an edimax 7811un with the latest version of this driver and the card is only seeing 2.4ghz channels on a network where I know there are 5ghz cells. The module was inserted wo options. Am I doing something wrong or is this a bug?

**Comment by leifj** [comment]
turns out my card is not dual-band. sorry.

**Comment by pvaret** [comment]
Thank you for the report... and the resolution! I love it when things work out without my getting involved. :)
