### ISSUE TITLE
probleme de connection avec awus36nhr

### ISSUE THREAD

**Issue by chechii29** [pvaret/rtl8192cu-fixes#53]
bonjour j ai utiliser votre driver pour brancher ma carte awus36nhr tout semble fonctionner liste importante de reseau wifi capté mais lorsque je cherche a me connecter la carte cherche pendant une minute puis se deconnecte alors que la carte intergrée au portable se connecte facilement a mon telephone sur un autre post j ai vu le meme probleme pouriez vous m aider a resoudre ce pb je ne comprend pas trop l anglais du coup j ai peut etre pas compris la manip sachant que votre driver a marché au premier essai mais j ai fais la manip pour le power management depuis il ne se connecte plus et je ne sais pas comment l annulé je debute avec l informatique linux merci d avance

**Comment by pvaret** [comment]
Bonjour,

Il est important de noter que ce repo ne contient que le driver fourni par Realtek, juste repackagé pour en faciliter l'installation sur Ubuntu. Si le driver de Realtek ne marche pas avec un device donné, alors ce repo ne marchera pas non plus. Désolé.

Pour annuler le paramétrage du power management, faire: `sudo rm /etc/modprobe.d/8192cu-disable-power-management.conf` et recharger le driver (ou redémarrer).
