### ISSUE TITLE
No connection after wake up

### ISSUE THREAD

**Issue by ayrton04** [pvaret/rtl8192cu-fixes#57]
I'm using a TRENDnet TEW-648UBM N150 Micro Wireless Adapter, and your driver works very well (thank you!), except when I put my computer to sleep and wake it back up. When it wakes up, the adapter either doesn't show up in the network manager drop-down in the menu bar, or there are no networks listed. Rebooting fixes the problem, and the adapter connects immediately. Relevant system specs:

- uname -a output: Linux Ayrbox 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux]
- ASRock X99 Extreme4 LGA 2011-v3 Intel X99 motherboard
- TRENDnet TEW-648UBM N150 USB WiFi adapter

Apologies for posting a new issue if there's just a configuration change that I need to make.

**Comment by pvaret** [comment]
Hi,

Glad to hear the driver works well for you! Have you tried the power management workaround listed in the README? (I don't think it will change anything, but you never know.)

**Comment by ayrton04** [comment]
Whoops, that did in fact do the trick, sorry. Thanks very much!

**Comment by pvaret** [comment]
Oh, but you're welcome! Sorry about the delay in replying, though. I have not had much time to take care of this repository lately.
