### ISSUE TITLE
WPA2 Authentication failed

### ISSUE THREAD

**Issue by mbakturk** [pvaret/rtl8192cu-fixes#62]
Hi. First of all thanks for this driver.

I installed this driver according to readme instructions and it works well if the connection is insecure. However when I try to connect WPA2 connection, it always ask me connection password.

My card info is shown below
Bus 001 Device 003: ID 0bda:817f Realtek Semiconductor Corp. RTL8188RU 802.11n WLAN Adapter

Linux mint 17.3 kernel version: 4.2

**Comment by pvaret** [comment]
As a late update: the rtl8xxxu driver from the mainline kernel works pretty fine these days. That's what I'm using now myself. You may still have to troubleshoot NetworkManager, though: in particular, consider [disabling power management](https://askubuntu.com/questions/695867/disable-wifi-power-management/961460#961460). Disabling it made the rtlxxxu driver work well for me.
