### ISSUE TITLE
TP-Link WN8200ND

### ISSUE THREAD

**Issue by AppoPro** [pvaret/rtl8192cu-fixes#64]
Guys how about support TP-Link WN8200ND ?

**Comment by pvaret** [comment]
As a rule of thumb, if a device is not supported by the Realtek-provided driver, it will not be supported by this one. We aren't rewriting that driver, we're just trying to make it easier to install on recent distros. You may have better luck with the actually rewritten driver in the newly release kernel 4.4, though.
