### ISSUE TITLE
Any chance of making 8192cu compatible with hostapd?

### ISSUE THREAD

**Issue by davepuchyr** [pvaret/rtl8192cu-fixes#65]
Hostapd works with the stock rtl8192cu (and rtl8192ce) modules.  I get 

"nl80211: Could not configure driver mode" 

with the 8192cu module; see below for more info. Any chance of making 8192cu compatible with hostapd?  Does it need to be dependent on the mac80211 module?

[root@ocho etc]# uname -a
Linux ocho 4.1.13-100.fc21.x86_64 #1 SMP Tue Nov 10 13:13:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

[root@ocho etc]# lsusb -v -d 7392:7811

Bus 004 Device 004: ID 7392:7811 Edimax Technology Co., Ltd EW-7811Un 802.11n Wireless Adapter [Realtek RTL8188CUS]
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x7392 Edimax Technology Co., Ltd
  idProduct          0x7811 EW-7811Un 802.11n Wireless Adapter [Realtek RTL8188CUS]
  bcdDevice            2.00
  iManufacturer           1 Realtek
  iProduct                2 802.11n WLAN Adapter
  iSerial                 3 00e04c000001
  bNumConfigurations      1

[root@ocho etc]# modinfo 8192cu
filename:       /lib/modules/4.1.13-100.fc21.x86_64/extra/8192cu.ko
version:        v4.0.2_9000.20130911
author:         Realtek Semiconductor Corp.
description:    Realtek Wireless Lan Driver
license:        GPL
srcversion:     340C0C60435AA0500D61BF0
alias:          usb:v0BDAp8186d*dc*dsc*dp*ic*isc*ip*in*
.
.
.
alias:          usb:v0BDAp8191d*dc*dsc*dp*ic*isc*ip*in*
depends:        
vermagic:       4.1.13-100.fc21.x86_64 SMP mod_unload 
parm:           rtw_ips_mode:The default IPS mode (int)
parm:           ifname:The default name to allocate for first interface (charp)
parm:           if2name:The default name to allocate for second interface (charp)
parm:           rtw_initmac:charp
parm:           rtw_channel_plan:int
parm:           rtw_chip_version:int
parm:           rtw_rfintfs:int
parm:           rtw_lbkmode:int
parm:           rtw_network_mode:int
parm:           rtw_channel:int
parm:           rtw_mp_mode:int
parm:           rtw_wmm_enable:int
parm:           rtw_vrtl_carrier_sense:int
parm:           rtw_vcs_type:int
parm:           rtw_busy_thresh:int
parm:           rtw_ht_enable:int
parm:           rtw_cbw40_enable:int
parm:           rtw_ampdu_enable:int
parm:           rtw_rx_stbc:int
parm:           rtw_ampdu_amsdu:int
parm:           rtw_lowrate_two_xmit:int
parm:           rtw_rf_config:int
parm:           rtw_power_mgnt:int
parm:           rtw_low_power:int
parm:           rtw_wifi_spec:int
parm:           rtw_special_rf_path:int
parm:           rtw_antdiv_cfg:int
parm:           rtw_enusbss:int
parm:           rtw_hwpdn_mode:int
parm:           rtw_hwpwrp_detect:int
parm:           rtw_hw_wps_pbc:int
parm:           rtw_max_roaming_times:The max roaming times to try (uint)
parm:           rtw_force_iol:Force to enable IOL (bool)
parm:           rtw_mc2u_disable:int
parm:           rtw_mac_phy_mode:int
parm:           rtw_80211d:int
parm:           rtw_notch_filter:0:Disable, 1:Enable, 2:Enable only for P2P (uint)

[root@ocho etc]# lsmod 
Module                  Size  Used by
ccm                    20480  4 
8021q                  32768  0 
.
.
.
8192cu                536576  0 
rtl_usb                20480  0 
rtl8192ce              57344  0 
rtl_pci                28672  1 rtl8192ce
rtl8192c_common        53248  1 rtl8192ce
mac80211              724992  4 rtl_pci,rtl_usb,rtlwifi,rtl8192ce
cfg80211              557056  2 mac80211,rtlwifi
.
.
.
video                  20480  0 

[root@ocho etc]# journalctl -u hostapd.service
Jan 23 13:05:05 systemd[1]: Starting Hostapd IEEE 802.11 AP, IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator...
Jan 23 13:05:05 hostapd[2395]: Configuration file: /etc/hostapd/hostapd.conf
Jan 23 13:05:05 hostapd[2395]: nl80211: Could not configure driver mode
Jan 23 13:05:05 hostapd[2395]: nl80211: deinit ifname=wlp0s29u1u2 disabled_11b_rates=0
Jan 23 13:05:05 hostapd[2395]: nl80211 driver initialization failed.
Jan 23 13:05:05 hostapd[2395]: wlp0s29u1u2: interface state UNINITIALIZED->DISABLED
Jan 23 13:05:05 hostapd[2395]: wlp0s29u1u2: AP-DISABLED
Jan 23 13:05:05 hostapd[2395]: hostapd_free_hapd_data: Interface wlp0s29u1u2 wasn't started
Jan 23 13:05:05 systemd[1]: hostapd.service: control process exited, code=exited status=1
Jan 23 13:05:05 systemd[1]: Failed to start Hostapd IEEE 802.11 AP, IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator.
Jan 23 13:05:05 systemd[1]: Unit hostapd.service entered failed state.
Jan 23 13:05:05 systemd[1]: hostapd.service failed.

**Comment by dlech** [comment]
Not with this repository. There has been a renewed effort for a mainline kernel driver recently, which is your best chance. https://github.com/torvalds/linux/blob/master/drivers/net/wireless/realtek/rtl8xxxu/Kconfig

**Comment by davepuchyr** [comment]
Thanks
