### ISSUE TITLE
Works great with kernel 4.3

### ISSUE THREAD

**Issue by kursusHC** [pvaret/rtl8192cu-fixes#66]
Hi, 

Just want to say thank you for your driver. No more disconnection and speed doubled with a RTL8192CU device on a 4.3 kernel. Thanks !

**Comment by Lazer32** [comment]
I just wanted to say thank you as well!  I'm running Ubuntu on the 4.4 Kernel and it is working flawlessly there as well!  I'm using the Edimax EW-7811Un (7392:7811)

Before using this driver my wireless connection would drop within 5 minutes making it completely unusable.

**Comment by pvaret** [comment]
Thank you for the kind words. Much appreciated. :)
