### ISSUE TITLE
doesn't compile on aarch64 or with newer versions of gcc

### ISSUE THREAD

**Issue by briselec** [pvaret/rtl8192cu-fixes#73]
add #include <net/ip6_checksum.h> in rtw_br_ext.c 
remove extern keyword from ieee80211.h on lines 1197, 1202 and 1208

**Comment by CGarces** [comment]
Fixed with b618ae85b29e660bcd0f986c44a7e9ea0c2170b5
Please @pvaret close it

**Comment by pvaret** [comment]
Good catch, thanks. :)
