### ISSUE TITLE
doesn' t work  on linux 4.4.0 (ubuntu 16.04)

### ISSUE THREAD

**Issue by mapelo** [pvaret/rtl8192cu-fixes#75]
doesn' t work  on linux 4.4.0 (ubuntu 16.04)

Solution: You need to add rtl8xxxu into blacklist-native-rtl8192.conf

**Comment by pvaret** [comment]
Thanks for the heads-up.

Isn't kernel 4.4 supposed to fix its own rtl8192cu driver, making this one obsolete, though? (Haven't tested it yet.)

**Comment by kyawthusoe3142** [comment]
@mapelo How to add rtl8xxxu into blacklist-native-rtl8192.conf?

**Comment by dlech** [comment]
See <https://github.com/pvaret/rtl8192cu-fixes/blob/master/blacklist-native-rtl8192.conf>

Add the line:

    install rtl8xxxu /bin/false

**Comment by kyawthusoe3142** [comment]
Thank you! It worked.

**Comment by dlech** [comment]
Fixed: https://github.com/pvaret/rtl8192cu-fixes/commit/fcb0eccb68509c3d64ac9f35a3f1ab3ff83cf5a9

**Comment by otakuryo** [comment]
2 weeks and you save me, I love you *-*
(Arch 4.7.4)

**Comment by dcdeiv** [comment]
Ehrm no. Xubuntu 16.04 LTS it doesn't work. Wifi now doesn't exists anymore. I had to reinstall Xubuntu.

**Comment by ajith4ab** [comment]
@mapelo cannot find rtl8xxxu into blacklist-native-rtl8192.conf?
