### ISSUE TITLE
Extra steps needed for 0bda:819a device

### ISSUE THREAD

**Issue by jf248** [pvaret/rtl8192cu-fixes#82]
Thanks for this solution. Needed an extra step for my device (0bda:819a) so sharing if useful for others.

`$ lsusb` gives:
`Bus 001 Device 003: ID 0bda:819a Realtek Semiconductor Corp.`

I installed Ubuntu 16.04 on old Windows Lenovo IdeaCentre-A530 which has an internal USB wifi adapter. Wifi adapter appeared in Network Manager and could see wireless networks but couldn't connect (or dropped very quickly).

After going through the steps here and rebooting, wifi adapter no longer visible in Network Manager. Problem is a missing reference to my specific device. To add it:

`$ echo 'install 8192cu modprobe --ignore-install 8192cu ; /bin/echo "0bda 819a" > /sys/bus/usb/drivers/rtl8192cu/new_id' | sudo tee /etc/modprobe.d/8192cu.conf`

then

`$ sudo modprobe -v 8192cu`

Wifi starts working. To get the 8192cu module to load at boot:

`$ echo '8192cu' | sudo tee -a /etc/modules-load.d/modules.conf`

HT: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1102179

**Comment by pvaret** [comment]
That USB id is not explicitly supported by the driver but we can add it. What's the name and chipset of your device?

Also: the rtl8xxxu driver from the mainline kernel works pretty fine these days. That's what I'm using now myself. You may still have to troubleshoot NetworkManager, though: in particular, consider [disabling power management](https://askubuntu.com/questions/695867/disable-wifi-power-management/961460#961460). Disabling it made the rtlxxxu driver work well for me.
