### ISSUE TITLE
ASUS USB-N13 WiFi Dongle

### ISSUE THREAD

**Issue by sunshinertoo** [pvaret/rtl8192cu-fixes#90]
ASUS USB-N13 WiFi Dongle works also now.
Thanks!

**Comment by dlech** [comment]
Great! What is the output of `lsusb` for this device?

**Comment by sunshinertoo** [comment]
Bus 001 Device 012: ID 0b05:17ab ASUSTek Computer, Inc. USB-N13 802.11n Network Adapter (rev. B1) [Realtek RTL8192CU]
mind the rev. B1

**Comment by dlech** [comment]
Thanks. I have added this to the README.

**Comment by sunshinertoo** [comment]
To install newer kernels one can do:
dkms remove 8192cu/1.10 --all
en then reinstall 8192cu, and, before rebooting:
update-initramfs -u -k 4.5.4
for the new kernel (vmlinuz-4.5.4 used here)
