### ISSUE TITLE
Losing packages on ubuntu 15.10

### ISSUE THREAD

**Issue by sacherus** [pvaret/rtl8192cu-fixes#92]
Hi,
I have tplink tl-wn823n I installed your workaround. However, connection seems a little bit "turbulent" and I'm losing some packages: 

with wifi:
--- o.pl ping statistics ---
109 packets transmitted, 95 received, 12% packet loss, time 108213ms
rtt min/avg/max/mdev = 57.720/273.805/1174.826/202.602 ms, pipe 2

with ethernet:
--- o.pl ping statistics ---
91 packets transmitted, 91 received, 0% packet loss, time 90122ms
rtt min/avg/max/mdev = 55.309/56.694/58.092/0.588 ms

with built-in wifi:
--- o.pl ping statistics ---
108 packets transmitted, 108 received, 0% packet loss, time 107162ms
rtt min/avg/max/mdev = 57.626/62.660/80.776/4.073 ms

lsmod:
sacherus@ZalmanZ3:~$ lsmod | grep 8192cu
8192cu                536576  0

Is it "normal" behaviour of this adapter?

**Comment by pvaret** [comment]
You may have to troubleshoot NetworkManager: in particular, consider [disabling power management](https://askubuntu.com/questions/695867/disable-wifi-power-management/961460#961460). Disabling it made the driver work well for me. That said, you may also want to switch to the rtl8xxxu driver from the mainline kernel, which works pretty fine these days.
