### ISSUE TITLE
libnl can't seem to get ssid and link quality

### ISSUE THREAD

**Issue by hyqneuron** [pvaret/rtl8192cu-fixes#96]
https://github.com/i3/i3status/issues/91

Above is an issue at i3status, and it was reported on a 8192cu device. I'm having the same problem here. Basically libnl is not able to get the ssid and link quality. i3status recently went from libiw to libnl, so ssid and link quality no longer get displayed in i3status.

I'm reproducing problems reported in mentioned issue. I'm on Ubuntu 16.04 on kernel 4.4.0-28.

Going back to libiw with i3status got it fixed. But the guys at i3status said libnl is the way to go. Something for you guys to consider.

**Comment by pvaret** [comment]
Probably this has to do with the features we dropped while patching Realtek's driver to make it work on recent kernels.

At any rate, you probably want to switch to the rtl8xxxu driver from the mainline kernel, which works pretty well these days. You may still have to troubleshoot NetworkManager, though: in particular, consider [disabling power management](https://askubuntu.com/questions/695867/disable-wifi-power-management/961460#961460). Disabling it made the rtlxxxu driver work well for me.
