### ISSUE TITLE
Adaptive Bit Rate not working. Stuck at 54 Mb/s 

### ISSUE THREAD

**Issue by shahidali55** [pvaret/rtl8192cu-fixes#97]
Hi All,

I have compiled this module and blacklisted the linux rtlxxxx modules. The 8192cu module loads up correctly and connect to my 'g' only router correctly. But moving the client away from the router increases dropped packets exponentially and iwconfig reports "Bit Rate:54 Mb/s" all the way till the connection eventually drops.

lsusb:
`Bus 001 Device 002: ID 0bda:8176 Realtek Semiconductor Corp. RTL8188CUS 802.11n WLAN Adapter`

lsmod:

```
Module                  Size  Used by
mac80211              358429  0
8192cu                520861  0
```

modinfo 8192cu:

```
filename:       /lib/modules/3.4.112-sun8i/kernel/net/wireless/8192cu.ko
version:        v4.0.2_9000.20130911
author:         Realtek Semiconductor Corp.
description:    Realtek Wireless Lan Driver
license:        GPL
srcversion:     3009C5B6392017400B6CBF3
```

cat /etc/modprobe.d/8192cu.conf:
`options 8192cu rtw_power_mgnt=0 rtw_enusbss=0 rtw_ips_mode=1 rtw_hwpwrp_detect=0`

**Comment by pvaret** [comment]
This repo is only a port of Realtek's driver to recent kernel. Actual issues with the drivers itself should be taken upstream, to Realtek themselves. Sorry!
